### ISSUE TITLE
do not "create" user when just querying a (non-existing) user

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-admin-portal#29]
Currently when at the admin panel you try to get information about a user that does not exist, the user will be "created", i.e. an entry will be added to the DB and user_id will be listed on the users tab. This is not really good!

**Comment by fkooman** [comment]
* remove all users that have no associated certificates and/or 2fa methods

**Comment by fkooman** [comment]
This issue was triggered "automatically" when user IDs contained a special character, i.e. a "+" symbol. A "ghost" user was created when clicking on the user ID in the admin portal. This particular issue was fixed already in https://github.com/eduvpn/vpn-admin-portal/commit/4eccd2538d1def8479940ed82d56c1898eaa8611

**Comment by ghost** [comment]
merged with vpn-user-portal.
